#
# @copyright Copyright (c) 2020 ApertureData Inc.
#

import os
Import('env')

prom_amb_env = env.Clone()
prom_amb_env.Replace(
    CPPPATH = [ 'src',
                os.getenv('JSONCPP_INCLUDE', default=''),
                os.getenv('AD_COMM_INCLUDE',   default='../../include'),
                os.getenv('AD_CLIENT_INCLUDE',   default='../../include'),
                os.getenv('PROMETHEUS_CPP_CORE_INCLUDE', default=''),
                os.getenv('PROMETHEUS_CPP_PULL_INCLUDE', default=''),
              ],
    LIBS =    [ 'comm',
                'aperturedb-client',
                'prometheus-cpp-core',
                'prometheus-cpp-pull',
              ],
    LIBPATH = [ '/usr/local/lib/',
                os.getenv('AD_COMM_LIB',         default='../../lib'),
                os.getenv('AD_CLIENT_LIB',   default='../../lib'),
                os.getenv('JSONCPP_LIB',         default=''),
                os.getenv('PROMETHEUS_CPP_LIB',  default=''),
              ],
)

src = [ 
  'src/ClientCollector.cc',
  'src/PromConfig.cc',
  'src/PromServer.cc',
]

prom_amb_env.Program('prometheus_ambassador', ['prometheus_ambassador.cc'] + src)

test_env = prom_amb_env.Clone()
test_env.Replace(
    LIBS = prom_amb_env['LIBS'] + ['gtest', 'pthread', 'protobuf'],
    CPPPATH = prom_amb_env['CPPPATH'] + ['../../test', '../../src'],
)

test_src = [ 'test/ClientCollectorTests.cc', 'test/main.cc' ]

test_obj = [ 
  '../../test/Barrier.o',
  'src/ClientCollector.o',
  'src/PromConfig.o',
  'src/PromServer.o',
  test_src,
]

test_env.Program('prometheus_ambassador_test', test_obj)


