#
# @copyright Copyright (c) 2020 ApertureData Inc.
#
import os
Import('env')

send_query_env = env.Clone()

send_query_env.Replace(
    CPPPATH =
		env.adbPackageIncludePaths('ad_comm','ad_client','prometheus-cpp','nlohmann/json','glog'),
    LIBPATH = ['/usr/local/lib/']+
		env.adbPackageLibPaths( 'ad_comm','ad_client','prometheus-cpp','glog'),
    LIBS =    ['libglog', 'comm', 'aperturedb-client', 'glog'],
)

files = [ 'send_query.cc' ]

send_query_env.Program('send_query', files)
