#
# @copyright Copyright (c) 2020 ApertureData Inc.
#
import os
Import('env')

send_query_env = env.Clone()

send_query_env.Replace(
    CPPPATH = [ os.getenv('AD_COMM_INCLUDE',       default='../../include'),
                os.getenv('AD_CLIENT_INCLUDE',     default='../../include'),
                os.getenv('NLOHMANN_JSON_INCLUDE', default='/usr/include'),
                os.getenv('GLOG_INCLUDE',          default=''),
                os.getenv('PROTOBUF_INCLUDE',      default='')
    ],
    LIBPATH = ['/usr/local/lib/',
                os.getenv('AD_COMM_LIB',           default='../../lib'),
                os.getenv('AD_CLIENT_LIB',         default='../../lib'),
                os.getenv('GLOG_LIB',              default=''),
                os.getenv('PROTOBUF_LIB',          default='')
    ],
    LIBS =    [ 'comm',
                'aperturedb-client',
                'glog',
                'protobuf'
    ],
)

files = [ 'send_query.cc' ]

send_query_env.Program('send_query', files)
